'----------------SETUP-----------
'[
Dim invApp As Inventor.Application
	invApp = ThisApplication
Dim oDrawDoc As DrawingDocument
	oDrawDoc  = ThisDoc.Document
Dim oActiveSheet As Sheet
	oActiveSheet = oDrawDoc.ActiveSheet
Dim oSheet As Sheet
	oSheet = oDrawDoc.ActiveSheet
'Dim Xcoord = 62.25
'Dim Ycoord = 19.8
'Dim width = oSheet.Width
'Dim height = oSheet.Height
'MessageBox.Show("width" & width & "height" & height)
'Dim LS = 0.4
Dim oTG As Inventor.TransientGeometry = invApp.TransientGeometry
Dim leaderPoints As ObjectCollection = invApp.TransientObjects.CreateObjectCollection()
Dim oNote As LeaderNote 
']
'__________________________________________________________________________________________________________________________________________________________
'--------------Locating Points on the Page----------------
'[
	'Locating Page Corners
		'[
			'Bottom Left Corner of Page
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1, 1))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(0, 0)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Bottom Left of Page" & vbCrLf & "(0 cm,0 cm)")
					leaderPoints.Clear()
				']
				
			'Bottom Right Corner of Page	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(83.1, -1))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(84.1, 0)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Bottom Right of Page" & vbCrLf & "(84.1 cm,0 cm)")
					leaderPoints.Clear()
				']
				
			'Top Left Corner of Page
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1, 58.4))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(0, 59.4)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Top Left of Page" & vbCrLf & "(0 cm,59.4 cm)")
					leaderPoints.Clear()
				']
				
			'Top Right Corner of Page
				'[
					leaderPoints.Add(oTG.CreatePoint2d(83.1, 58.4))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(84.1, 59.4)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Top Right of Page" & vbCrLf & "(84.1 cm,59.4 cm)")
					leaderPoints.Clear()
				']
		']
		
	'Locating Border Corners
	'[
		'Bottom Left Corner of Border	
			'[
				leaderPoints.Add(oTG.CreatePoint2d(1.5, 3))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(2, 2)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Bottom Left of Border" & vbCrLf & "(2 cm,2 cm)")
				leaderPoints.Clear()
			']
			
		'Bottom Right Corner of Border
			'[
				leaderPoints.Add(oTG.CreatePoint2d(82.6, 3))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(82.1, 2)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Bottom Right of Border" & vbCrLf & "(82.1 cm,2 cm)")
				leaderPoints.Clear()
			']			
			
		'Top Left Corner of Border	
			'[
				leaderPoints.Add(oTG.CreatePoint2d(1.5, 56.4))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(2, 57.4)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Top Left of Border" & vbCrLf & "(2 cm,57.4 cm)")
				leaderPoints.Clear()
			']
			
		'Top Right Corner of Border	
			'[
				leaderPoints.Add(oTG.CreatePoint2d(81.1, 56.4))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(82.1, 57.4)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Top Right of Border" & vbCrLf & "(82.1 cm,57.4 cm)")
				leaderPoints.Clear()
			']
	']
		
	'Locating Horizontal Ticks
		'[
			'First Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(8, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "First Tick" & vbCrLf & "(7.00833 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'Second Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(15.1, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(14.01666, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Second Tick" & vbCrLf & "(14.01666 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'Third Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*3, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*3, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Third Tick" & vbCrLf & "(21.02499 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'Fourth Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*4, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*4, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Fourth Tick" & vbCrLf & "(28.03332 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'Fifth Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*5, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*5, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Fifth Tick" & vbCrLf & "(35.04165 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'Sixth Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*6, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*6, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Sixth Tick" & vbCrLf & "(42.04998 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'Seventh Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*7, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*7, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Seventh Tick" & vbCrLf & "(49.05831 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'8th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*8, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*8, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Eighth Tick" & vbCrLf & "(56.06664 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'9th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*9, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*9, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Nineth Tick" & vbCrLf & "(63.07497 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'10th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*10, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*10, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Tenth Tick" & vbCrLf & "(70.0833 cm, 2 cm)")
					leaderPoints.Clear()
				']
			'11th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*11, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*11, 2)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Eleventh Tick" & vbCrLf & "(77.09163 cm, 2 cm)")
					leaderPoints.Clear()
				']
		']
	'Locating Vertical Ticks
		'[
			'First Tick on the Vertical Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1.75, 8.00833))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(2, 7.425)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "First Tick" & vbCrLf & "(2, 7.43)")
					leaderPoints.Clear()
				']		
			'Second Tick on the Vertical Border	
				'[
						leaderPoints.Add(oTG.CreatePoint2d(1.75, 15.85))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(2, 14.85)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Second Tick" & vbCrLf & "(2, 14.85)")
						leaderPoints.Clear()
				']
			'Third Tick on the Vertical Border	
				'[
						leaderPoints.Add(oTG.CreatePoint2d(1.75, 7.425*3+1))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(2, 7.425*3)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Third Tick" & vbCrLf & "(2, 22.28)")
						leaderPoints.Clear()
				']
			'Fourth Tick on the Vertical Border	
				'[
						leaderPoints.Add(oTG.CreatePoint2d(1.75, 1.5+7.425*4))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(2, 7.425*4)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Fourth Tick" & vbCrLf & "(2, 29.7)")
						leaderPoints.Clear()
				']
			'Fifth Tick on the Vertical Border	
				'[
						leaderPoints.Add(oTG.CreatePoint2d(1.75, 1+7.425*5))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(2, 7.425*5)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Fifth Tick" & vbCrLf & "(2, 37.13)")
						leaderPoints.Clear()
				']
			'Sixth Tick on the Vertical Border	
				'[
						leaderPoints.Add(oTG.CreatePoint2d(1.75, 1+7.425*6))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(2, 7.425*6)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Sixth Tick" & vbCrLf & "(2, 44.55)")
						leaderPoints.Clear()
				']
			'Seventh Tick on the Vertical Border	
				'[
						leaderPoints.Add(oTG.CreatePoint2d(1.75,  1+7.425*7))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(2, 7.425*7)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "Seventh Tick" & vbCrLf & "(2, 51.98)")
						leaderPoints.Clear()
				']
']
