'----------------SETUP-----------
'[
Dim invApp As Inventor.Application
	invApp = ThisApplication
Dim oDrawDoc As DrawingDocument
	oDrawDoc  = ThisDoc.Document
Dim oActiveSheet As Sheet
	oActiveSheet = oDrawDoc.ActiveSheet
Dim oSheet As Sheet
	oSheet = oDrawDoc.ActiveSheet
'Dim Xcoord = 62.25
'Dim Ycoord = 19.8
'Dim width = oSheet.Width
'Dim height = oSheet.Height
'MessageBox.Show("width" & width & "height" & height)
'Dim LS = 0.4
Dim oTG As Inventor.TransientGeometry = invApp.TransientGeometry
Dim leaderPoints As ObjectCollection = invApp.TransientObjects.CreateObjectCollection()
Dim oNote As LeaderNote 
']
'__________________________________________________________________________________________________________________________________________________________
'--------------Locating Points on the Page----------------

	'Locating Page Corners
		'[
			'Bottom Left Corner of Page
				'[
					leaderPoints.Add(oTG.CreatePoint2d(.5, 0.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(0, 0)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(0 cm,0 cm)")
					leaderPoints.Clear()
				']
				
			'Bottom Right Corner of Page	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(83.1, -1))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(84.1, 0)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints,"(84.1 cm,0 cm)")
					leaderPoints.Clear()
				']
				
			'Top Left Corner of Page
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1, 58.9))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(0, 59.4)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(0 cm,59.4 cm)")
					leaderPoints.Clear()
				']
				
			'Top Right Corner of Page
				'[
					leaderPoints.Add(oTG.CreatePoint2d(83.1, 58.9))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(84.1, 59.4)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(84.1 cm,59.4 cm)")
					leaderPoints.Clear()
				']
		']
		
	'Locating Border Corners
	'[
		'Bottom Left Corner of Border	
			'[
				leaderPoints.Add(oTG.CreatePoint2d(1.5, 2))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(1, 1)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm,1 cm)")
				leaderPoints.Clear()
			']
			
		'Bottom Right Corner of Border
			'[
				leaderPoints.Add(oTG.CreatePoint2d(83.6, 2))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(83.1, 1)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(83.1 cm,1 cm)")
				leaderPoints.Clear()
			']
			

			
		'Top Left Corner of Border	
			'[
				leaderPoints.Add(oTG.CreatePoint2d(1.5, 57.4))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(1, 58.4)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm,58.4 cm)")
				leaderPoints.Clear()
			']
			
		'Top Right Corner of Border	
			'[
				leaderPoints.Add(oTG.CreatePoint2d(83.6, 57.4))    'controls text location 
				leaderPoints.Add(oTG.CreatePoint2d(83.1, 58.4)) 'controls arrow location 'the page is measured in CM
				oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints,"(86.1 cm,58.4 cm)")
				leaderPoints.Clear()
			']
	']
		
	'Locating Horizontal Ticks
		'[
			'First Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(8, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(7.00833 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'Second Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(15.1, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(14.01666, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(14.01666 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'Third Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*3, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*3, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(21.02499 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'Fourth Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*4, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*4, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(28.03332 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'Fifth Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*5, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*5, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(35.04165 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'Sixth Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*6, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*6, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(42.04998 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'Seventh Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*7, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*7, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(49.05831 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'8th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*8, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*8, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(56.06664 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'9th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*9, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*9, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(63.07497 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'10th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*10, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*10, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(70.0833 cm, 1 cm)")
					leaderPoints.Clear()
				']
			'11th Tick on the Horizontal Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1+7.00833*11, 1.5))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(7.00833*11, 1)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(77.09163 cm, 1 cm)")
					leaderPoints.Clear()
				']
		']
	'Locating Vertical Ticks
		'[
			'First Tick on the Vertical Border	
				'[
					leaderPoints.Add(oTG.CreatePoint2d(1.5, 8.00833))    'controls text location 
					leaderPoints.Add(oTG.CreatePoint2d(1, 7.425)) 'controls arrow location 'the page is measured in CM
					oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm, 7.425 cm)")
					leaderPoints.Clear()
				']
				
			'Second Tick on the Vertical Border	
					'[
						leaderPoints.Add(oTG.CreatePoint2d(1.5, 15.85))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(1, 14.85)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm, 14.85 cm)")
						leaderPoints.Clear()
					']
			'Third Tick on the Vertical Border	
					'[
						leaderPoints.Add(oTG.CreatePoint2d(1.5, 7.425*3+1))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(1, 7.425*3)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm, 22.275 cm)")
						leaderPoints.Clear()
					']
			'Fourth Tick on the Vertical Border	
					'[
						leaderPoints.Add(oTG.CreatePoint2d(1.5, 1+7.425*4))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(1, 7.425*4)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm, 29.7 cm)")
						leaderPoints.Clear()
					']
			'Fifth Tick on the Vertical Border	
					'[
						leaderPoints.Add(oTG.CreatePoint2d(1.5, 1+7.425*5))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(1, 7.425*5)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm, 37.125 cm)")
						leaderPoints.Clear()
					']
			'Sixth Tick on the Vertical Border	
					'[
						leaderPoints.Add(oTG.CreatePoint2d(1.5, 1+7.425*6))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(1, 7.425*6)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm, 44.55 cm)")
						leaderPoints.Clear()
					']
			'Seventh Tick on the Vertical Border	
					'[
						leaderPoints.Add(oTG.CreatePoint2d(1.5,  1+7.425*7))    'controls text location 
						leaderPoints.Add(oTG.CreatePoint2d(1, 7.425*7)) 'controls arrow location 'the page is measured in CM
						oNote = oSheet.DrawingNotes.LeaderNotes.Add(leaderPoints, "(1 cm, 51.975 cm)")
						leaderPoints.Clear()
					']